Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2004"
    config.vm.box_version = "3.1.16"
    config.vm.network "public_network"
    config.vm.hostname = "monitoring-server"
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
    end

    config.vm.provision "shell", path: "./install.sh"

end